# Deop when quit
deop-when-quit: false

# Disable join & quit message
disable-join-quit-msg: true

# Chat coloring
chat-coloring: true

chat-colors:
  # Colors to use in different groups
  default:
    -
      char: ">"
      color: "GREEN"
  donor:
    -
      char: ">"
      color: "GREEN"
    -
      char: "'"
      color: "RED"
  admin:
    -
      char: ">"
      color: "GREEN"
    -
      char: "!"
      color: "RED"

# Enable plugin query?
enable-plugin-query: true

# Enable suicide?
enable-suicide: true

# Enable custom help?
enable-help: true

# Help message
help:
  - "&6China2B2T!"