# Deop when quit (TODO)
deop-when-quit: false

# Disable join & quit message
disable-join-quit-msg: true

# Chat coloring
chat-coloring: true

# Enable plugin query?
enable-plugin-query: true

# Enable suicide?
enable-suicide: true

# Enable custom help?
enable-help: true

# Help message
help:
  - "&6China2B2T!"