# Deop when quit
deop-when-quit: false

# Disable join & quit message
disable-join-quit-msg: true

# Chat coloring
chat-coloring: true

chat-colors:
  # Colors to use in different groups
  default:
    -
      char: ">"
      color: "a"
  donor:
    -
      char: ">"
      color: "a"
    -
      char: "'"
      color: "6"
  admin:
    -
      char: ">"
      color: "a"
    -
      char: "!"
      color: "c"
    -
      char: "'"
      color: "6"

# Enable plugin query?
enable-plugin-query: true

# Enable suicide?
enable-suicide: true

# Enable custom help?
enable-help: true

# Help message
help:
  - "&6China2B2T!"

pm-denied:
  - "陈氏"