main: org.china2b2t.twilightx.TwilightX
name: TwilightX
version: 1.0
author: Rabbit0w0
api-version: 1.12
commands:
  kill:
    description: Suicide
  plugins:
    description: Get a list of the plugins
    aliases: [pl, plugin]
  twiload:
    description: Reload TwilightX
  msg:
    description: Send a PM
    aliases: [tell, message, pm, whisper]
  pluginmgr:
    description: Plugin manager
    aliases: [plm, plmgr]
  mute:
    description: Mute someone
  unmute:
    description: Unmute someone